### ISSUE TITLE
Search Functionality .

### ISSUE THREAD

**Issue by akhan118** [akhan118/Coding-Crash-Course#10]
Hi,

Do we need a search functionality, any thoughts?

```

// cleaned lines 90 through 119
    public function actionTest()
    {
      if(YII::$app->request->get())
      {
        //  $model = new Product();

        $term =YII::$app->request->get('search');

        $rows = (new \yii\db\Query())
    ->select('*')
    ->from('products')
    ->where(['like', 'productName', $term])
    ->all();
  
        var_dump($rows);
        // 
        //   $searchResults = Products::find()->where(['ProductName'=>$term])->all();
        //
        //
        // var_dump($searchResults);

// this is a test comment CV
        // return $this->render('searchResults', [
        //     'results' => $searchResults,
        // ]);
      }
    }
```

**Comment by isjxique** [comment]
Hey, I think that search functionality is great but maybe it doesn't necessarily have to be the central part of the site especially if the shop is dedicated to a small number of items (i.e. only shirts). There are even some great sites without any search functionality: 

[BAPE](https://bape.com/webstore/?brandid=Mg==&categoryid=MjM=&itemid=&color=&stock=MQ==&popup=1)
[Cartier](http://www.en.cartier.com/home.html)

**Comment by akhan118** [comment]
Hi,

Yes, I agree.  Those are both good design and I like BAPE more.

**Comment by TechnoSayge** [comment]
Thanks Ahmad
