### ISSUE TITLE
Web Store View

### ISSUE THREAD

**Issue by isjxique** [akhan118/Coding-Crash-Course#16]
Hey, so i was thinking that we use the search queries that we currently have to build up a web store view like the one the [BAPE](https://bape.com/webstore/?brandid=Mg==&categoryid=MjM=&itemid=&color=&stock=MQ==&popup=1). We can start by making a page and then start messing around with adding the css/html to make it look like the BAPE store view.

**Comment by TechnoSayge** [comment]
Thanks Ish!

**Comment by isjxique** [comment]
How to create a new page on yii2
https://www.cloudways.com/blog/creating-hello-world-page-in-yii2/

**Comment by akhan118** [comment]
Thanks, Ish!  I think a store front like BAPE would look well.
