### ISSUE TITLE
TOP level category 

### ISSUE THREAD

**Issue by akhan118** [akhan118/Coding-Crash-Course#23]

**Comment by RayBook** [comment]
Ahmad,  Would you kindly provide details and explain the issue.

**Comment by akhan118** [comment]
I will, once I figure it out... I put it there as a reminder. but basically, there might be a need for a top level category. example Women, Men, Unisex,  Kids and so on

**Comment by isjxique** [comment]
Is it possible to have functionality like the BAPE page where clicking on the Men, T-Shirt, and M buttons bring updates the items in the view that match those specifications?

**Comment by akhan118** [comment]
oh yeah, that would be really awesome. I'm going to explore it by next week and push something for testing. thanks, Ish !
