### ISSUE TITLE
Table - Field Database (Test)

### ISSUE THREAD

**Issue by RayBook** [akhan118/Coding-Crash-Course#24]
Running a test to learn how to upload a WorkBench Database file.  Let me know if the upload file is useful for a developer?
[Table - Fields eComm.pdf](https://github.com/akhan118/Coding-Crash-Course/files/1203242/Table.-.Fields.eComm.pdf)

**Comment by akhan118** [comment]
it looks pretty good. I like it.

**Comment by RayBook** [comment]
Uploads are disabled.
File uploads require push access to this repository.

**Comment by isjxique** [comment]
Hey ray, I think you will have to submit a pull request.
